# action.yml
name: 'Markdown Reference Link Action'
description: 'Transforms reference links in markdown files to inline links'
author: 'Steve Calnan <steve@datadoghq.com>'

inputs:
  source-path:
    description: 'Path to the file containing reference links'
    required: true
  destination-path:
    description: 'Path to write the transformed file'
    required: true

outputs:
  result: 
    description: 'Number of links transformed'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-path }}
    - -o
    - ${{ inputs.destination-path }}
